### ISSUE TITLE
How to add ItemTouchHelper with binding-collection-adapter

### ISSUE THREAD

**Issue by hweilong** [evant/binding-collection-adapter#184] opened 2020-03-14 00:54 UTC
animation not work well

**Comment by evant** [comment] 2020-03-14 18:24
Thank you for reporting your issue. In order to look into it, can you please provide a sample project and clear steps to reproduce?

**Comment by evant** [comment] 2020-05-22 21:48
Closing this because not enough info was provided, feel free to re-open if you are still having issues.

**Closed by evant** 2020-05-22 21:48 UTC
Labels: needs info
